### ISSUE TITLE
"pierfrancescosoffriti.github.io has control of your pointer. Press Esc to take back control."

### ISSUE THREAD

**Issue by sergiks** [PierfrancescoSoffritti/pierfrancescosoffritti.com#29]
Hi, after recent FireFox update I started noticing privacy warning that appear and hide shortly. They read "pierfrancescosoffriti.github.io has control of your pointer. Press Esc to take back control."

[Screenshot](https://imgur.com/a/XZ4dQj7)

This happens even on a new tab blank standard page , and is related to Dev Tools opened.  Inparticular, the warning appears when hovering over Dev Tools tabs.

Maybe you have an idea, why could that happen, and how does Mozilla browser reference the disabled github pages site of yours?

Kind regards,
Sergei Sokolov.

**Comment by PierfrancescoSoffritti** [comment]
I guess it's for the full screen web projects? what are you using my website for exactly?

**Comment by sergiks** [comment]
This strange issue has already disappeared after next FireFox updates. Now on FF 94.0.2 – no more alerts like that.
The issue was not connected to your web site: I don't think I ever visited the site before the alert started appearing and I managed to take a screen shot of it to spell the address correctly.
My blind guess is that maybe parts of your code were somehow used in FireFox browser.

**Comment by PierfrancescoSoffritti** [comment]
ok, glad it's fixed :)
